# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  slack: circleci/slack@2.2.0
workflows:
  # START DEVOPS CONFIG
  DevOps:
    jobs:
      - checkout:
          name: "Checkout"
      - env:
          name: "Environment"
          requires:
            - "Checkout"
      - dependencies:
          name: "Dependencies"
          skip: false
          requires:
            - "Environment"
      - config:
          name: "Config"
          skip: false
          CONFIG: ".env"
          requires:
            - "Environment"
      - test:
          name: "Unit Test"
          skip: true
          requires:
            - "Dependencies"
            - "Config"
      - e2e:
          name: "E2E Test"
          skip: true
          requires:
            - "Dependencies"
            - "Config"
      - lint:
          name: "Lint"
          skip: false
          requires:
            - "Dependencies"
            - "Config"
      - audit:
          name: "Audit"
          skip: false
          requires:
            - "Dependencies"
            - "Config"
      - build:
          name: "Build"
          skip: false
          requires:
            - "Unit Test"
            - "E2E Test"
            - "Lint"
            - "Audit"
          BUILD_ALPHA: "npm run build"
          BUILD_BETA: "npm run build"
          BUILD_STABLE: "npm run build"
      - publish:
          name: "Publish"
          skip: false
          context: "publisher"
          requires:
            - "Build"
          filters:
            branches:
              only:
                - /release\/.*/
      - master:
          name: "Update Master"
          skip: false
          context: "global"
          requires:
            - Publish
      - slack_msg:
          name: "Slack Notification"
          skip: false
          context: "global"
          requires:
            - Publish
# END DEVOPS CONFIG
jobs:
  checkout:
    docker:
      - image: cimg/node:18.4
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Release Branch Check
          command: |
            export RELEASE="release/.*"
            if [[ "$(git branch | grep \* | cut -d ' ' -f2)" =~ $RELEASE ]] ; then
              echo "Release branch - checking out last tag $(git describe --abbrev=0)" ;
              git checkout $(git describe --abbrev=0)
            else
              echo "Not release branch - moving forward." ;
            fi
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  env:
    docker:
      - image: cimg/node:18.4
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: "Setup Variables"
          command: |
            mkdir -p .circleci/ && touch .circleci/env
            export TAG="$(git describe --abbrev=0)"
            export ALPHA="^v?([0-9]+\d*)\.([0-9]+\d*)\.([0-9]+\d*)-alpha((\.[0-9]+)|$)$"
            export BETA="^v?([0-9]+\d*)\.([0-9]+\d*)\.([0-9]+\d*)-beta((\.[0-9]+)|$)$"
            export STABLE="^v?([0-9]+\d*)\.([0-9]+\d*)\.([0-9]+\d*)$"
            if [[ "$TAG" =~ $ALPHA ]] ; then
              echo "export TAG=ALPHA" >> .circleci/env
            elif [[ "$TAG" =~ $BETA ]] ; then
              echo "export TAG=BETA" >> .circleci/env
            elif [[ "$TAG" =~ $STABLE ]] ; then
              echo "export TAG=STABLE" >> .circleci/env
            else
              echo "Unknown tag $TAG"
            fi
      - persist_to_workspace:
          root: ~/project
          paths:
            - .circleci
  dependencies:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Dependencies"
        default: false
        type: boolean
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-
      - run:
          name: Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
  config:
    docker:
      - image: cimg/node:18.4
    parameters:
      CONFIG:
        description: "Config File"
        default: "/dev/null"
        type: string
      skip:
        description: "Skip Config"
        default: false
        type: boolean
    environment:
      CONFIG: << parameters.CONFIG >>
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Load Config
          command: |
            source .circleci/env
            if [[ "$TAG" = "ALPHA" ]] ; then
              echo $ALPHA_CONFIG | base64 -d > "$CONFIG"
            elif [[ "$TAG" = "BETA" ]] ; then
              echo $BETA_CONFIG | base64 -d > "$CONFIG"
            elif [[ "$TAG" = "STABLE" ]] ; then
              echo $STABLE_CONFIG | base64 -d > "$CONFIG"
            else
              echo $DEVELOP_CONFIG | base64 -d > "$CONFIG"
            fi
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  test:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Unit Test"
        default: false
        type: boolean
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Setup
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -qq -y google-chrome-stable
      - run:
          name: Unit Test
          command: npm run test
  e2e:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip E2E Test"
        default: false
        type: boolean
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Setup
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -qq -y google-chrome-stable
      - run:
          name: E2E Test
          command: npm run e2e
  lint:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Lint"
        default: false
        type: boolean
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint
          command: npm run lint
  audit:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Audit"
        default: false
        type: boolean
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Audit
          command: npm audit --production
  build:
    docker:
      - image: cimg/node:18.4
    parameters:
      BUILD_ALPHA:
        description: "The Alpha Build Command"
        default: ""
        type: string
      BUILD_BETA:
        description: "The Beta Build Command"
        default: ""
        type: string
      BUILD_STABLE:
        description: "The Stable Build Command"
        default: ""
        type: string
      skip:
        description: "Skip Build"
        default: false
        type: boolean
    environment:
      BUILD_ALPHA: << parameters.BUILD_ALPHA >>
      BUILD_BETA: << parameters.BUILD_BETA >>
      BUILD_STABLE: << parameters.BUILD_STABLE >>
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Release Branch Check
          command: |
            export RELEASE="release/.*"
            if [[ "$(git branch | grep \* | cut -d ' ' -f2)" =~ $RELEASE ]] ; then
              echo "Release branch - checking out last tag $(git describe --abbrev=0)" ;
              git checkout $(git describe --abbrev=0)
            else
              echo "Not release branch - moving forward." ;
            fi
      - run:
          name: Select Build Command
          command: |
            source .circleci/env
            if [[ "$TAG" = "ALPHA" ]] ; then
              echo "export BUILD=\"$BUILD_ALPHA\"" >> .circleci/env
            elif [[ "$TAG" = "BETA" ]] ; then
              echo "export BUILD=\"$BUILD_BETA\"" >> .circleci/env
            elif [[ "$TAG" = "STABLE" ]] ; then
              echo "export BUILD=\"$BUILD_STABLE\"" >> .circleci/env
            else
              echo "export BUILD=\"$BUILD_STABLE\"" >> .circleci/env
            fi
      - run:
          name: Run Build
          command: |
            source .circleci/env
            eval "$BUILD"
      - run:
          name: Packaging Artifacts
          command: tar czvf /tmp/build.tar.gz `pwd`
      - store_artifacts:
          path: /tmp/build.tar.gz
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
  publish:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Publish"
        default: false
        type: boolean
    working_directory: ~/project
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - attach_workspace:
          at: ~/project
      - run:
          name: Release Branch Check
          command: |
            export RELEASE="release/.*"
            if [[ "$(git branch | grep \* | cut -d ' ' -f2)" =~ $RELEASE ]] ; then
              echo "Release branch - checking out last tag $(git describe --abbrev=0)" ;
              git checkout $(git describe --abbrev=0)
            else
              echo "Not release branch - moving forward." ;
            fi
      - attach_workspace:
          at: ~/project
      - run:
          name: "Setup Variables"
          command: |
            source .circleci/env
            if [[ "$TAG" = "ALPHA" ]] ; then
              echo "Publishing alpha library"
            elif [[ "$TAG" = "BETA" ]] ; then
              echo "Publishing beta library"
            elif [[ "$TAG" =~ "STABLE" ]] ; then
              echo "Publishing production library"
            else
              echo "Unknown tag $TAG"
              exit 1
            fi
      - run:
          name: Set up NPM Authentication
          command: |
            npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
      - run:
          name: Publish to NPM
          command: npm publish
  master:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Master Update"
        default: false
        type: boolean
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - checkout
      - run:
          name: Release Branch Check
          command: |
            export RELEASE="release/.*"
            if [[ "$(git branch | grep \* | cut -d ' ' -f2)" =~ $RELEASE ]] ; then
              echo "Release branch - checking out last tag $(git describe --abbrev=0)" ;
              git checkout $(git describe --abbrev=0)
            else
              echo "Not release branch - moving forward." ;
            fi
      - run:
          name: Evaluate Tags
          command: |
            export STABLE="^v?([0-9]+\d*)\.([0-9]+\d*)\.([0-9]+\d*)$"
            if [[ "$(git describe --abbrev=0)" =~ $STABLE ]] ; then
              echo "Update master" ;
            else
              echo "Do not update master" ;
              circleci-agent step halt
            fi
      - run:
          name: Setup Git
          command: |
            git config user.email "engineering@wearewiser.com"
            git config user.name "CircleCI"
      - run:
          name: Update Master
          command: git branch -f master HEAD
      - run:
          name: Checkout Master
          command: git checkout master
      - run:
          name: Push Master
          command: |
            echo "$(echo $CIRCLE_REPOSITORY_URL | sed s/:/\\//g | sed s/git@/https\:\\/\\/${GITHUB_TOKEN}@/g)"
            git push "$(echo $CIRCLE_REPOSITORY_URL | sed s/:/\\//g | sed s/git@/https\:\\/\\/${GITHUB_TOKEN}@/g)" master
  slack_msg:
    docker:
      - image: cimg/node:18.4
    parameters:
      skip:
        description: "Skip Slack Release Notification"
        default: false
        type: boolean
    steps:
      - when:
          condition: <<parameters.skip>>
          steps:
            - run:
                name: Skip
                command: circleci-agent step halt
      - checkout
      - slack/notify:
          message: "Release ${CIRCLE_PROJECT_REPONAME}@$(git describe --abbrev=0) published"
          color: "#5031aa"
          webhook: "${SLACK_HOOK}"
          include_visit_job_action: true
          include_project_field: true
